name = "baseline"
units = [ 0.02, 0.04, 0.08, 0.16, 0.32, 0.64 ]
include_utt = true
random_seek = true
use_mask = true

sample_rate       = 16000
segment_duration  = 9.6
trailing_duration = 0.005

ssl_path = "pretrained/w2v_large_lv_fsh_swbd_cv_fixed.pt"
ssl_dim  = 1024
ssl_tuning = true

[dataset]
scp_train_wav = "PartialSpoof/scp/train-wav.scp"
scp_train_lab = "PartialSpoof/label_PartialSpoof_train.txt"
scp_dev_wav = "PartialSpoof/scp/dev-wav.scp"
scp_dev_lab = "PartialSpoof/label_PartialSpoof_dev.txt"

[optimizer]
learning_rate = 0.00001

[scheduler]
step_size = 10
lr_decay_factor = 0.5
